In [2]:
from sklearn.datasets import load_wine
import pandas as pd

X=load_wine().data
df=pd.DataFrame(X,columns=load_wine().feature_names)
y=load_wine().target
df

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0      14.23        1.71  2.43               15.6      127.0           2.80   
1      13.20        1.78  2.14               11.2      100.0           2.65   
2      13.16        2.36  2.67               18.6      101.0           2.80   
3      14.37        1.95  2.50               16.8      113.0           3.85   
4      13.24        2.59  2.87               21.0      118.0           2.80   
..       ...         ...   ...                ...        ...            ...   
173    13.71        5.65  2.45               20.5       95.0           1.68   
174    13.40        3.91  2.48               23.0      102.0           1.80   
175    13.27        4.28  2.26               20.0      120.0           1.59   
176    13.17        2.59  2.37               20.0      120.0           1.65   
177    14.13        4.10  2.74               24.5       96.0           2.05   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     od280/od315_of_diluted_wines  proline  
0                            3.92   1065.0  
1                            3.40   1050.0  
2                            3.17   1185.0  
3                            3.45   1480.0  
4                            2.93    735.0  
..                            ...      ...  
173                          1.74    740.0  
174                          1.56    750.0  
175                          1.56    835.0  
176                          1.62    840.0  
177                          1.60    560.0  

[178 rows x 13 columns]

In [3]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
for i in load_wine().feature_names:
    df[i]=le.fit_transform(df[i])
df 

alcohol  malic_acid  ash  alcalinity_of_ash  magnesium  total_phenols  \
0        118          43   44                 12         45             73   
1         65          49   18                  1         21             68   
2         63          71   63                 32         22             73   
3        121          59   49                 21         33             95   
4         67          81   75                 45         37             73   
..       ...         ...  ...                ...        ...            ...   
173       92         131   46                 42         16             23   
174       76         113   48                 51         23             30   
175       68         119   29                 40         39             17   
176       64          81   38                 40         39             22   
177      112         117   69                 55         17             42   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity  hue  \
0           107                    11               87               81   49   
1            91                     9               31               56   50   
2           115                    13               96               83   48   
3           122                     7               84              109   30   
4            89                    20               66               53   49   
..          ...                   ...              ...              ...  ...   
173          12                    30               22              108   10   
174          19                    24               40              104   16   
175          17                    24               35              125    6   
176          16                    31               45              120    7   
177          20                    33               35              119    8   

     od280/od315_of_diluted_wines  proline  
0                             120       94  
1                             102       92  
2                              86      101  
3                             104      116  
4                              73       66  
..                            ...      ...  
173                            22       67  
174                            10       68  
175                            10       74  
176                            14       75  
177                            13       40  

[178 rows x 13 columns]

In [4]:
df.shape,y.shape

((178, 13), (178,))

In [5]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(df,y,test_size=0.2,random_state=0)


# SKLEarn

In [6]:
from sklearn.neural_network import MLPClassifier

mlp=MLPClassifier(max_iter=1000,activation='relu')

In [7]:
mlp.fit(X_train,y_train)

MLPClassifier(max_iter=1000)

In [8]:
from sklearn.metrics import accuracy_score

y_pred=mlp.predict(X_test)
accuracy_score(y_test,y_pred)

1.0

In [9]:
from sklearn.metrics import confusion_matrix

# help(confusion_matrix)

confusion_matrix(y_test,y_pred)

array([[14,  0,  0],
       [ 0, 16,  0],
       [ 0,  0,  6]], dtype=int64)

# TF

In [19]:
import tensorflow as tf 
import numpy as np

In [52]:
ann=tf.keras.models.Sequential()


In [53]:
ann.add(tf.keras.layers.Dense(units=13, activation='relu'))

In [54]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [55]:
ann.add(tf.keras.layers.Dense(units=1, activation='relu'))

In [56]:
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])


In [57]:
help(ann.fit)

Help on method fit in module keras.src.engine.training:

fit(x=None, y=None, batch_size=None, epochs=1, verbose='auto', callbacks=None, validation_split=0.0, validation_data=None, shuffle=True, class_weight=None, sample_weight=None, initial_epoch=0, steps_per_epoch=None, validation_steps=None, validation_batch_size=None, validation_freq=1, max_queue_size=10, workers=1, use_multiprocessing=False) method of keras.src.engine.sequential.Sequential instance
    Trains the model for a fixed number of epochs (dataset iterations).
    
    Args:
        x: Input data. It could be:
          - A Numpy array (or array-like), or a list of arrays
            (in case the model has multiple inputs).
          - A TensorFlow tensor, or a list of tensors
            (in case the model has multiple inputs).
          - A dict mapping input names to the corresponding array/tensors,
            if the model has named inputs.
          - A `tf.data` dataset. Should return a tuple
            of either `(

In [58]:
ann.fit(X_train,y_train,epochs=150)

Epoch 1/150
5/5 [==============================] - 1s 2ms/step - loss: 0.4308 - accuracy: 0.3803
Epoch 2/150
5/5 [==============================] - 0s 1ms/step - loss: 0.4308 - accuracy: 0.3803
Epoch 3/150
5/5 [==============================] - 0s 2ms/step - loss: 0.4308 - accuracy: 0.3803
Epoch 4/150
5/5 [==============================] - 0s 2ms/step - loss: 0.4308 - accuracy: 0.3803
Epoch 5/150
5/5 [==============================] - 0s 2ms/step - loss: 0.4308 - accuracy: 0.3803
Epoch 6/150
5/5 [==============================] - 0s 2ms/step - loss: 0.4308 - accuracy: 0.3803
Epoch 7/150
5/5 [==============================] - 0s 2ms/step - loss: 0.4308 - accuracy: 0.3803
Epoch 8/150
5/5 [==============================] - 0s 2ms/step - loss: 0.4308 - accuracy: 0.3803
Epoch 9/150
5/5 [==============================] - 0s 2ms/step - loss: 0.4308 - accuracy: 0.3803
Epoch 10/150
5/5 [==============================] - 0s 2ms/step - loss: 0.4308 - accuracy: 0.3803
Epoch 11/150
5/5 [===========

In [59]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

2/2 [==============================] - 0s 2ms/step
[[1 0]
 [1 2]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 0]
 [1 2]
 [1 1]
 [1 1]
 [1 2]
 [1 2]
 [1 0]
 [1 1]
 [1 2]
 [1 1]
 [1 0]
 [1 0]
 [1 1]
 [1 0]
 [1 1]
 [1 0]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 2]
 [1 0]
 [1 0]
 [1 1]
 [1 0]
 [1 0]
 [1 0]]


In [61]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(y_test, y_pred2)

[[ 0 14  0]
 [ 0 16  0]
 [ 0  6  0]]
[0 2 1 0 1 1 0 2 1 1 2 2 0 1 2 1 0 0 1 0 1 0 0 1 1 1 1 1 1 2 0 0 1 0 0 0] [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]
